### ISSUE TITLE
I'm new and I'm really interested in software engineering I had a course on udemy but it's seem haven't really understand it well please I need a mentor

### ISSUE THREAD

**Issue by ghost** [ashfaquekhan/WiFi-Pishing#1]
I'm new and I'm really interested in software engineering I had a course on udemy but it's seem haven't really understand it well please I need a mentor

_Originally posted by @Drew3040 in https://github.com/sindresorhus/awesome/issues/2097#issuecomment-1094928191_

**Comment by 166dawe** [comment]
> I'm new and I'm really interested in software engineering I had a course on udemy but it's seem haven't really understand it well please I need a mentor
> 
> _Originally posted by @Drew3040 in https://github.com/sindresorhus/awesome/issues/2097#issuecomment-1094928191_
